# Generated by Django 4.0.5 on 2022-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.EmailField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
