# Generated by Django 4.0.5 on 2022-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_organization_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
