# Generated by Django 4.0.5 on 2022-09-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_organization_number_employess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='number_employess',
            new_name='number_employees',
        ),
    ]
