# Generated by Django 4.0.5 on 2022-06-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('due_amount', models.FloatField(blank=True, default=0.0, max_length=255, null=True)),
                ('invoice_status', models.CharField(choices=[('SENT', 'Sent'), ('PAYMENT_SCHEDULED', 'Payment Scheduled'), ('UNSENT', 'Unsent')], default='UNSENT', max_length=255)),
                ('untaxed_amount', models.FloatField(blank=True, default=0.0, max_length=255, null=True)),
                ('vat_amount', models.FloatField(blank=True, default=0.0, max_length=255, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('curreny', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
            },
        ),
    ]
