# Generated by Django 4.0.5 on 2022-07-04 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='po_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='curreny',
            field=models.CharField(default='KES', max_length=255),
        ),
    ]
