# Generated by Django 4.0.5 on 2022-07-04 07:30

import apps.invoice.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_alter_customer_industry_name'),
        ('invoice', '0002_remove_invoice_po_number_invoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='customer.customer'),
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.invoice.models.invoice_attachment)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_attachment', to='invoice.invoice')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
