# Generated by Django 4.0.5 on 2022-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_customer_invoiceattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-id',), 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoice'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('PAYMENT_SCHEDULED', 'Payment Scheduled'), ('UNSENT', 'Unsent'), ('PAYMENT_DONE', 'Payment Done')], default='UNSENT', max_length=255),
        ),
    ]
