# Generated by Django 4.0.5 on 2022-07-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='reminder',
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminders',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
