# Generated by Django 4.0.5 on 2022-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoice_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
