# Generated by Django 4.0.5 on 2022-07-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoice_reminder_invoice_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_online_payment',
            field=models.BooleanField(default=False),
        ),
    ]
