# Generated by Django 4.0.5 on 2022-07-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_is_online_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('Manually', 'Manually'), ('Card', 'Card')], default='Manually', max_length=255)),
                ('tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_transaction', to='invoice.invoice')),
            ],
        ),
    ]
