# Generated by Django 4.0.5 on 2022-07-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoicetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransaction',
            name='payment_type',
            field=models.CharField(choices=[('Manually', 'Manually'), ('Online', 'Online')], default='Manually', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer'), ('M-Pesa', 'M-Pesa'), ('Debit Card', 'Debit Card'), ('Other', 'Other')], default='Cash', max_length=255),
        ),
    ]
