# Generated by Django 4.0.5 on 2022-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_paymentmethods_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='auto_payment_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
