# Generated by Django 4.0.5 on 2022-08-05 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0014_paymentmethods_auto_payment_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesAndPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roles_permission_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
