# Generated by Django 4.0.5 on 2022-08-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_rolesandpermissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolesandpermissions',
            old_name='industry',
            new_name='roles',
        ),
    ]
