# Generated by Django 4.0.5 on 2022-08-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_invoicetransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Credit/Debit/Atm'), (2, 'M-Pesa')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('PAYMENT_SCHEDULED', 'Payment Scheduled'), ('UNSENT', 'Unsent'), ('PAYMENT_DONE', 'Payment Done'), ('PARTIALLY_PAID', 'Partially Paid')], default='UNSENT', max_length=255),
        ),
    ]
