# Generated by Django 4.0.5 on 2022-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_alter_carddetail_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
