# Generated by Django 4.0.5 on 2022-08-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_notification_invoice_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
