# Generated by Django 4.0.5 on 2022-09-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0029_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-id',)},
        ),
    ]
