# Generated by Django 4.0.5 on 2022-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_alter_notification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_users', models.IntegerField(blank=True, default=0, null=True)),
                ('storage', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
