# Generated by Django 4.0.5 on 2022-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
