# Generated by Django 4.0.5 on 2022-09-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_alter_subscription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='no_of_users',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='storage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
