# Generated by Django 4.0.5 on 2022-09-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_alter_subscription_no_of_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreminder',
            options={'ordering': ('days',)},
        ),
    ]
