# Generated by Django 4.0.5 on 2022-09-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0035_alter_paymentreminder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreminder',
            options={},
        ),
    ]
