# Generated by Django 4.0.5 on 2022-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_alter_paymentreminder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetail',
            name='m_pesa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='cvv_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
