# Generated by Django 4.0.5 on 2022-09-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0037_carddetail_m_pesa_alter_carddetail_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetail',
            name='payment_type',
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('M-Pesa', 'M-Pesa'), ('Debit Card', 'Debit Card'), ('Other', 'Other')], default='Cash', max_length=255),
        ),
    ]
