# Generated by Django 4.0.5 on 2022-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0039_subscription_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
