# Generated by Django 4.0.5 on 2022-09-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0040_alter_carddetail_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetail',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='carddetail',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carddetail',
            name='expiry_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carddetail',
            name='expiry_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
