# Generated by Django 4.0.5 on 2022-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0042_usersubscription_usersubscriptiontransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
