# Generated by Django 4.0.5 on 2022-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0043_alter_usersubscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetail',
            name='is_auto_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
