# Generated by Django 4.0.5 on 2022-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('pin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('industry_name', models.CharField(max_length=30)),
                ('billing_address', models.CharField(max_length=100)),
                ('billing_city', models.CharField(max_length=30)),
                ('billing_country', models.CharField(max_length=30)),
                ('shipping_address', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=30)),
                ('shipping_country', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('primary_name', models.CharField(blank=True, max_length=30, null=True)),
                ('primary_role', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_on'],
            },
        ),
    ]
