# Generated by Django 4.0.5 on 2022-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.PositiveSmallIntegerField(choices=[(1, 'Business'), (2, 'Goverment'), (3, 'Individual'), (4, 'Other')], default=4)),
                ('full_name', models.CharField(max_length=30)),
                ('pin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('industry_name', models.CharField(max_length=30)),
                ('billing_address', models.TextField(max_length=254)),
                ('billing_city', models.CharField(max_length=30)),
                ('billing_country', models.CharField(max_length=30)),
                ('shipping_address', models.TextField(max_length=254)),
                ('shipping_city', models.CharField(max_length=30)),
                ('shipping_country', models.CharField(max_length=30)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('primary_name', models.CharField(blank=True, max_length=30, null=True)),
                ('primary_role', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('payments_term', models.PositiveSmallIntegerField(choices=[(1, 'Net 15'), (2, 'Net 30'), (3, 'Net 45'), (4, 'Net 60'), (5, 'Net 90'), (6, 'Other')], default=6)),
                ('payments_credit', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
                'ordering': ['-created_on'],
            },
        ),
    ]
