# Generated by Django 4.0.5 on 2022-06-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(max_length=254),
        ),
    ]
