# Generated by Django 4.0.5 on 2022-06-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_alternatecontact_alternate_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Business'), (2, 'Goverment'), (3, 'Individual'), (4, 'Other')], default=4),
        ),
    ]
