# Generated by Django 4.0.5 on 2022-06-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_alternate_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='open_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='outstanding_invoices',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='overdue_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='alternatecontact',
            name='alternate_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
