# Generated by Django 4.0.5 on 2022-06-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_user'),
        ('customer', '0008_alter_alternatecontact_alternate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='account.organization'),
        ),
    ]
