# Generated by Django 4.0.5 on 2022-06-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_role',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
