# Generated by Django 4.0.5 on 2022-06-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='billing_address',
            new_name='postal_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billing_city',
            new_name='postal_city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billing_country',
            new_name='postal_country',
        ),
        migrations.AlterField(
            model_name='alternatecontact',
            name='customer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customer'),
        ),
        migrations.CreateModel(
            name='PrimaryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(blank=True, max_length=30, null=True)),
                ('primary_role', models.CharField(blank=True, max_length=30, null=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('customer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primary_customer', to='customer.customer')),
            ],
        ),
    ]
