# Generated by Django 4.0.5 on 2022-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_billing_address_customer_postal_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='primary_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='primary_role',
        ),
        migrations.AlterField(
            model_name='primarycontact',
            name='primary_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='primarycontact',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
