# Generated by Django 4.0.5 on 2022-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_delete_primarycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
