# Generated by Django 4.0.5 on 2022-06-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customer_primary_email_customer_primary_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
