# Generated by Django 4.0.5 on 2022-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_customer_primary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatecontact',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
