# Generated by Django 4.0.5 on 2022-06-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
