# Generated by Django 4.0.5 on 2022-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_customer_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
