# Generated by Django 4.0.5 on 2022-06-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_customer_industry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='industry_name',
        ),
    ]
