# Generated by Django 4.0.5 on 2022-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_remove_customer_industry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='industry_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
